language: node_js
node_js: 6

env:
  global:
  - secure: "Du0DYGujLhM+5aT13X4DLc4GH7hE5nZ+s2qEdiwj4gyNc1zjB3z6qE9lqjL48W4nfbGh2BwjZa0ONSkWe0WnUNhcTpXPv9Y9DQr1+udEOT0xr71Eg7R5HCI3hyUnRuadUaTWe1nIfN6DBnVoMXam4RoupAg/9TdfNKte9jvfhwpN2afboKzcqcGMXqOSEqD9ea3200gDT2QQv7mR1BcqVk9ZQ67Ed9RyK88zrPx97KZkIDanlfWHuO5Jf8wuX7WRIzg8GPENLrJt1iLsPIZPyBl097Ewf2TRrPNhIzXUyAFEKSoeQ4K1rn+D8MawKuf1uiDlNZejdLZAXXonL+Ynw9rwt97c9e/kiJuE6yY5YFktoOWgAkmYg1WRkdkRULvZnjfKI84F5DadBqEj7bEXgmvCEU8hzxbmli70eQcVqenwXgzSEnni/tWzsxdewX8eakI+vRsWoqsaExoWQZS2XqAHiIMkESo51pvm4XE1AILj7I4Ui+4h1Zjuaz1bnrnCpAT5Ujn5ILunP9C3oZUIcstH8iNu/hiKdP5QwoQYMnpMYN0dh/nfphroYkKgvQ7YPaJYRGeLpIRv6/3OJ67iUUGosKIsErWrV36MumV5mLo/SWH0weTr4BvngLxHpcBjl1LVJZCheA7rYTCFvuHW5iVI+8f/GCYux0R59mksHtY="

deploy:
  skip_cleanup: true
  provider: script
  script: ./resources/publish.sh
  on:
    branch: cn
